spring:
  application:
    name: product-service
    # mysql database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/productdbtest
    username: root
    password: Rootpass123#
    driver-class-name: com.mysql.cj.jdbc.Driver

  # h2database
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver

#  config:
server:
  port: 8082
#    import: "optional:configserver:http://localhost:8088"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 0.1
